language: php

php:
  - 7.3
  - 7.4

before_script:
  - pecl install msgpack-2.1.0
  - cat /proc/cpuinfo
  - cat /proc/meminfo

script:
  - php benchmark-msgpack.php
  - php benchmark-json.php
  - php benchmark-json-assoc.php
