language: php

php:
  - 7.3
  - 7.4

before_script:
  - pecl install msgpack-2.1.0
  - cat /proc/cpuinfo

script:
  - php bin/benchmark-msgpack.php
  - php bin/benchmark-json.php
  - php bin/benchmark-json-assoc.php
